
(define (make-counter-pair)
  (define a 0)
  (define (incr)
    (set! a (+ a 1))
    a)
  (define (decr)
    (set! a (- a 1))
    a)
  (cons incr decr))

(define counter-pair (make-counter-pair))
(display ((car counter-pair)))
(newline)
(display ((car counter-pair)))
(newline)
(display ((cdr counter-pair)))
(newline)
(display ((cdr counter-pair)))
(newline)
